sudo: required

language: ruby

services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - echo "Docker Hub credentials are working"
  - docker build -t build-developer-rails-app .
  - docker run -it -d --publish 0.0.0.0:3000:3000 --name=build-developer-rails-app build-developer-rails-app
  - docker ps -a
  - docker run build-developer-rails-app /bin/sh -c "bundle exec rake"

before_script:
  - bundle exec rake db:setup

script:
  - bundle exec rake